### ISSUE TITLE
Сброс фильтра удаляет новые элементы

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/porten-app-onix#1]
Добавить новый элемент, и поиграться с фильтрами, то новые элементы удаляются. 
Из подобной ситуации можно найти несколько выходов
1. Сделать 2 массива в стейте, в один будут добавляться данные, а второй будет такой же как первый но отфильтрованый/отсортированый
2. Делать сортировку и фильтрацию на лету в функции `render`

**Comment by YourContender** [comment]
сделано )
