### ISSUE TITLE
!('') && 'uah'

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/porten-app-onix#10]
```
currency: !('') && 'uah',
country: !('') &&'Ukraine',
```

Наткнулся на такую странную запись, не понимаю что ты хотел этим получить

**Comment by YourContender** [comment]
Возникла проблема с defaultProps, пробовал передавать вот так:  
const { url, title, description, price, currency='uah', country='Ukraine' } = this.props.item;

Задумка какая, если валюту или страну при добавлении элемента не указали, то добавляется гривна и Украина, я проставил, вот как в строке выше, но это не сработало.
Потом я подумал как можно обойти это, придумал это - currency: !('') && 'uah' - тут задумка такая, что если строка пустая, то мы получим в значении гривны, а если не пустая, то само значение. Работает точно так же как и с defaultProps, но я уже понял, что фигню сделал(((( переделаю обязательно ))

**Comment by YourContender** [comment]
я завтра перечитаю за defaultProps, разберусь, по-любому где-то моя ошибка )
