### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/porten-app-onix#7]
```
  <Header/>
  <Nav/>
  <Routes>
      <Route path='/' element={<HomePage/>}/>
      <Route path='list' element={<ListPage/>}/>
  </Routes>
  ```

Я как раз сегодня в чате писал. Выносить хедер за роутер это не очень хорошая идея так как тогда у тебя пропадает возможность как либо управлять ними. Иногда на некоторых страницах нужно менять какие-то данные в layout, но когда это прописано как у тебя, то это проблематично

**Comment by YourContender** [comment]
сделано
